### ISSUE TITLE
delete this repository

### ISSUE THREAD

**Issue by ch-aurich** [lategoodbye/qca7000#1]
Since the software from this repository is now implemented in the linux kernel we should delete this repo here... 
If there is no one against deleting I will do it after one week (so after 15th Feb. 2016).

**Comment by lategoodbye** [comment]
It would be nice to preserve the history of the changes.

So i suggest to adopt the repository to @lategoodbye or rename it.

**Comment by ch-aurich** [comment]
Ok, moving the repo to your personal account is probably the best solution...
